### ISSUE TITLE
HTML parser is getting the wrong column.

### ISSUE THREAD

**Issue by marcelocastrobarbosa** [whateverpal/coinmetrics-tools#1] opened 2017-12-17 12:47 UTC
For instance, for price(usd) it is bringing volume, for marketcap(usd) it is getting prices.

**Comment by whateverpal** [comment] 2017-12-21 21:59
Hello, mcbarb, the issue is a bit unclear. As far as I can see, the order of data types in CSV header matches the order used by rows in CSV body.

**Comment by whateverpal** [comment] 2018-01-02 10:28
Closing due to issue being unclear and the absence of reporter's response

**Closed as completed by whateverpal** 2018-01-02 10:28 UTC
